# Generated by Django 5.0.6 on 2024-06-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_firstname_player_lastname_player_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='cleanSheets',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(null=True),
        ),
    ]
