# Generated by Django 5.0.6 on 2024-06-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_match_finalscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=800)),
                ('article', models.CharField(max_length=2000)),
                ('likes', models.IntegerField(null=True)),
                ('shares', models.IntegerField(null=True)),
            ],
        ),
    ]
